
runtime: nodejs10


env_variables:
  MONGODB_URI: "mongodb+srv://node_server:neWkPDlUsWrWYNqf@corona-in-bd-mongo-qcuic.gcp.mongodb.net/test?retryWrites=true&w=majority"
  USER_PUT_SECRET_KEY : "sdfbh435t64e5tdhjrftje5ye324r23klhgrsw2"



handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto